# Project 1

    We begin by loading the data

In [15]:
%matplotlib inline 
import numpy as np   # generic stuff
import matplotlib.pyplot as plt

#### REMOVE THIS LINE BEFORE SUBMISSION
import pandas as pd
#######################################################################

from lib.proj1_helpers import * #the helper provided for the project
from lib.cost import *

from implementations import * #our implementations of the functions done by us
import datetime
from helpers import * #helpers of exo 2
# Useful starting lines

%load_ext autoreload
%autoreload 2
%reload_ext autoreload

SyntaxError: invalid syntax (cost.py, line 7)

In [16]:
DATA_FOLDER = 'data/'

y, tx, ids = load_csv_data(DATA_FOLDER+'train.csv',sub_sample=False)

y_test, tx_test, ids_test = load_csv_data(DATA_FOLDER+'test.csv',sub_sample=False)

note that here we are only considering a sub_sample as the "True" value indicates

In [17]:
y

array([ 1., -1., -1., ...,  1., -1., -1.])

In [18]:
tx1 = tx.copy()
np.delete(tx1, [4,5,6,24,25,28], axis=1) 

array([[ 138.47 ,   51.655,   97.827, ...,   46.062,    1.24 ,  113.497],
       [ 160.937,   68.768,  103.235, ..., -999.   , -999.   ,   46.226],
       [-999.   ,  162.172,  125.953, ..., -999.   , -999.   ,   44.251],
       ..., 
       [ 105.457,   60.526,   75.839, ..., -999.   , -999.   ,   41.992],
       [  94.951,   19.362,   68.812, ..., -999.   , -999.   ,    0.   ],
       [-999.   ,   72.756,   70.831, ..., -999.   , -999.   ,    0.   ]])

In [1]:
txx = tx.copy().astype('float')
txx[txx == -999] = 'nan' # or use np.nan

NameError: name 'tx' is not defined

In [19]:
ids

array([100000, 100001, 100002, ..., 349997, 349998, 349999])

In [20]:
# illegal: 
pd.DataFrame(tx).head()

0        1        2       3       4        5        6      7       8   \
0  138.470   51.655   97.827  27.980    0.91  124.711    2.666  3.064  41.928   
1  160.937   68.768  103.235  48.146 -999.00 -999.000 -999.000  3.473   2.078   
2 -999.000  162.172  125.953  35.635 -999.00 -999.000 -999.000  3.148   9.336   
3  143.905   81.417   80.943   0.414 -999.00 -999.000 -999.000  3.310   0.414   
4  175.864   16.915  134.805  16.405 -999.00 -999.000 -999.000  3.891  16.405   

        9    ...        20       21   22       23       24       25       26  \
0  197.760   ...    -0.277  258.733  2.0   67.435    2.150    0.444   46.062   
1  125.157   ...    -1.916  164.546  1.0   46.226    0.725    1.158 -999.000   
2  197.814   ...    -2.186  260.414  1.0   44.251    2.053   -2.028 -999.000   
3   75.968   ...     0.060   86.062  0.0 -999.000 -999.000 -999.000 -999.000   
4   57.983   ...    -0.871   53.131  0.0 -999.000 -999.000 -999.000 -999.000   

       27       28       29  
0    1.24   -2.475  113.497  
1 -999.00 -999.000   46.226  
2 -999.00 -999.000   44.251  
3 -999.00 -999.000    0.000  
4 -999.00 -999.000    0.000  

[5 rows x 30 columns]

In [21]:
pd.DataFrame(tx1).head()

0        1        2       3       4        5        6      7       8   \
0  138.470   51.655   97.827  27.980    0.91  124.711    2.666  3.064  41.928   
1  160.937   68.768  103.235  48.146 -999.00 -999.000 -999.000  3.473   2.078   
2 -999.000  162.172  125.953  35.635 -999.00 -999.000 -999.000  3.148   9.336   
3  143.905   81.417   80.943   0.414 -999.00 -999.000 -999.000  3.310   0.414   
4  175.864   16.915  134.805  16.405 -999.00 -999.000 -999.000  3.891  16.405   

        9    ...        20       21   22       23       24       25       26  \
0  197.760   ...    -0.277  258.733  2.0   67.435    2.150    0.444   46.062   
1  125.157   ...    -1.916  164.546  1.0   46.226    0.725    1.158 -999.000   
2  197.814   ...    -2.186  260.414  1.0   44.251    2.053   -2.028 -999.000   
3   75.968   ...     0.060   86.062  0.0 -999.000 -999.000 -999.000 -999.000   
4   57.983   ...    -0.871   53.131  0.0 -999.000 -999.000 -999.000 -999.000   

       27       28       29  
0    1.24   -2.475  113.497  
1 -999.00 -999.000   46.226  
2 -999.00 -999.000   44.251  
3 -999.00 -999.000    0.000  
4 -999.00 -999.000    0.000  

[5 rows x 30 columns]

### Parameters

In [22]:
initial_w = np.zeros(tx.shape[1])
initial_w

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.])

In [23]:
gamma = 0.9
max_iters = 50
lambda_ = 0.5

# Methods

if we wanna compute it on a subset of the data:

In [24]:
tx1 = tx.copy()
tx1 = np.delete(tx1, [4,5,6,24,25,28], axis=1) 
tx_test1 = tx_test.copy()
tx_test1 = np.delete(tx_test1, [4,5,6,24,25,28], axis=1) 

## *LEAST-SQUARES

In [25]:
#losses, weights = least_squares_GD(y, tx, initial_w, max_iters, gamma);
losses, weights = least_squares_luca(y, tx1);
print('losses: \n',losses,'\n\n','weights: \n',weights)
weights = np.array(weights).T#[-1,:] uncomment for gradient descent
weights.shape

NameError: name 'least_squares_luca' is not defined

#### Prediction

In [ ]:
data = tx_test1
data.shape

In [ ]:
y_pred = predict_labels(weights, data)

In [ ]:
name = 'least square'
create_csv_submission(ids_test, y_pred, name)

## *Gradient descent     -------------------------------------------------------------------------------

In [119]:
#losses, weights = least_squares_GD(y, tx, initial_w, max_iters, gamma);
losses, weights = least_squares_luca(y, tx1);
print('losses: \n',losses,'\n\n','weights: \n',weights)
weights = np.array(weights).T#[-1,:] uncomment for gradient descent
weights.shape

1
losses: 
 0.348126106361 

 weights: 
 [  7.51452001e-05  -7.33646438e-03  -6.22154385e-03  -6.84702864e-04
   3.35884067e-01  -1.06096025e-04  -2.61085969e+00  -2.23029542e-01
   1.01461105e-01   1.87722058e-02   2.61953426e+00   2.80317235e-05
  -6.68666642e-04   2.62408395e+00   3.39452408e-04   1.15744012e-03
   3.76232517e-03   4.26009049e-04  -6.73907926e-04  -3.09396370e-01
   3.89871629e-04   1.10678902e-03  -1.93615993e-02   2.61017998e+00]


(24,)

#### Prediction

In [120]:
data = tx_test1
data.shape

(568238, 24)

In [121]:
y_pred = predict_labels(weights, data)

In [122]:
name = 'ye'
create_csv_submission(ids_test, y_pred, name)

## *Ridge regression    -------------------------------------------------------------------------------

In [130]:
gamma = 0.9
max_iters = 50
lambda_ = 1
#losses, weights = least_squares_GD(y, tx, initial_w, max_iters, gamma);
weights = ridge_regression(y, tx, lambda_);
print('losses: \n','\n\n','weights: \n',weights)
weights = np.array(weights).T#[-1,:] uncomment for gradient descent
weights.shape

losses: 
 

 weights: 
 [  2.60587944e-04  -9.09041953e-03  -2.05593759e-03  -2.07372712e-03
   4.16112316e-04   5.56555764e-04  -8.63582279e-03   1.49220972e-02
   8.84108508e-05   3.01001515e-03  -1.36439197e-02   2.91963352e-02
   5.90347247e-03   6.34020163e-03  -2.47827750e-04  -1.03790696e-03
   2.15291139e-03  -3.16656538e-04   7.13755800e-04   4.85803562e-03
   3.40155651e-04  -7.69669008e-04  -1.27454270e-02   1.51646839e-03
  -7.80900128e-04  -5.87028123e-04   3.16780195e-04   1.29177964e-03
   3.04952725e-04  -5.48271055e-03]


(30,)

#### Prediction

In [131]:
data = tx_test
data.shape

(568238, 30)

In [132]:
y_pred = predict_labels(weights, data)

In [133]:
name = 'ridge_regression'
create_csv_submission(ids_test, y_pred, name)