# Project 1

    We begin by loading the data

In [18]:
%matplotlib inline 
import numpy as np   # generic stuff
import matplotlib.pyplot as plt

#### REMOVE THIS LINE BEFORE SUBMISSION
import pandas as pd
#######################################################################

from lib.proj1_helpers import * #the helper provided for the project
from lib.cost import *

from implementations import * #our implementations of the functions done by us
import datetime
from helpers import * #helpers of exo 2
# Useful starting lines

%load_ext autoreload
%autoreload 2
%reload_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [2]:
DATA_FOLDER = 'data/'

y, tx, ids = load_csv_data(DATA_FOLDER+'train.csv',sub_sample=False)

y_test, tx_test, ids_test = load_csv_data(DATA_FOLDER+'test.csv',sub_sample=False)

note that here we are only considering a sub_sample as the "True" value indicates

In [3]:
y

array([ 1., -1., -1., ...,  1., -1., -1.])

In [4]:
tx1 = tx.copy()
np.delete(tx1, [4,5,6,24,25,28], axis=1) 

array([[ 138.47 ,   51.655,   97.827, ...,   46.062,    1.24 ,  113.497],
       [ 160.937,   68.768,  103.235, ..., -999.   , -999.   ,   46.226],
       [-999.   ,  162.172,  125.953, ..., -999.   , -999.   ,   44.251],
       ..., 
       [ 105.457,   60.526,   75.839, ..., -999.   , -999.   ,   41.992],
       [  94.951,   19.362,   68.812, ..., -999.   , -999.   ,    0.   ],
       [-999.   ,   72.756,   70.831, ..., -999.   , -999.   ,    0.   ]])

In [5]:
txx = tx.copy().astype('float')
txx[txx == -999] = 'nan' # or use np.nan

In [6]:
ids

array([100000, 100001, 100002, ..., 349997, 349998, 349999])

In [7]:
# illegal: 
pd.DataFrame(tx).head()

0        1        2       3       4        5        6      7       8   \
0  138.470   51.655   97.827  27.980    0.91  124.711    2.666  3.064  41.928   
1  160.937   68.768  103.235  48.146 -999.00 -999.000 -999.000  3.473   2.078   
2 -999.000  162.172  125.953  35.635 -999.00 -999.000 -999.000  3.148   9.336   
3  143.905   81.417   80.943   0.414 -999.00 -999.000 -999.000  3.310   0.414   
4  175.864   16.915  134.805  16.405 -999.00 -999.000 -999.000  3.891  16.405   

        9    ...        20       21   22       23       24       25       26  \
0  197.760   ...    -0.277  258.733  2.0   67.435    2.150    0.444   46.062   
1  125.157   ...    -1.916  164.546  1.0   46.226    0.725    1.158 -999.000   
2  197.814   ...    -2.186  260.414  1.0   44.251    2.053   -2.028 -999.000   
3   75.968   ...     0.060   86.062  0.0 -999.000 -999.000 -999.000 -999.000   
4   57.983   ...    -0.871   53.131  0.0 -999.000 -999.000 -999.000 -999.000   

       27       28       29  
0    1.24   -2.475  113.497  
1 -999.00 -999.000   46.226  
2 -999.00 -999.000   44.251  
3 -999.00 -999.000    0.000  
4 -999.00 -999.000    0.000  

[5 rows x 30 columns]

In [8]:
pd.DataFrame(tx1).head()

0        1        2       3       4        5        6      7       8   \
0  138.470   51.655   97.827  27.980    0.91  124.711    2.666  3.064  41.928   
1  160.937   68.768  103.235  48.146 -999.00 -999.000 -999.000  3.473   2.078   
2 -999.000  162.172  125.953  35.635 -999.00 -999.000 -999.000  3.148   9.336   
3  143.905   81.417   80.943   0.414 -999.00 -999.000 -999.000  3.310   0.414   
4  175.864   16.915  134.805  16.405 -999.00 -999.000 -999.000  3.891  16.405   

        9    ...        20       21   22       23       24       25       26  \
0  197.760   ...    -0.277  258.733  2.0   67.435    2.150    0.444   46.062   
1  125.157   ...    -1.916  164.546  1.0   46.226    0.725    1.158 -999.000   
2  197.814   ...    -2.186  260.414  1.0   44.251    2.053   -2.028 -999.000   
3   75.968   ...     0.060   86.062  0.0 -999.000 -999.000 -999.000 -999.000   
4   57.983   ...    -0.871   53.131  0.0 -999.000 -999.000 -999.000 -999.000   

       27       28       29  
0    1.24   -2.475  113.497  
1 -999.00 -999.000   46.226  
2 -999.00 -999.000   44.251  
3 -999.00 -999.000    0.000  
4 -999.00 -999.000    0.000  

[5 rows x 30 columns]

### Parameters

In [9]:
initial_w = np.zeros(tx.shape[1])
initial_w

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.])

In [10]:
gamma = 0.9
max_iters = 50
lambda_ = 0.5

# Methods

if we wanna compute it on a subset of the data:

In [11]:
tx1 = tx.copy()
tx1 = np.delete(tx1, [4,5,6,24,25,28], axis=1) 
tx_test1 = tx_test.copy()
tx_test1 = np.delete(tx_test1, [4,5,6,24,25,28], axis=1) 

## *LEAST-SQUARES

In [25]:
#losses, weights = least_squares_GD(y, tx, initial_w, max_iters, gamma);
losses, weights = least_squares_luca(y, tx1);
print('losses: \n',losses,'\n\n','weights: \n',weights)
weights = np.array(weights).T#[-1,:] uncomment for gradient descent
weights.shape

NameError: name 'least_squares_luca' is not defined

#### Prediction

In [ ]:
data = tx_test1
data.shape

In [ ]:
y_pred = predict_labels(weights, data)

In [ ]:
name = 'least square'
create_csv_submission(ids_test, y_pred, name)

## *Gradient descent     -------------------------------------------------------------------------------

In [20]:
losses, weights = least_squares_GD(y, tx, initial_w, max_iters, gamma);
#print('losses: \n',losses,'\n\n','weights: \n',weights)
weights

Gradient Descent(0/49): loss=0.5000000000000249, w0=96.89984559361932, w1=-24.555778743599888
Gradient Descent(1/49): loss=1626615419033.354, w0=-155002682.6256204, w1=72741799.34085234
Gradient Descent(2/49): loss=4.33126708561898e+25, w0=745146966592152.9, w1=-373816565608732.0
Gradient Descent(3/49): loss=1.1537452591800307e+39, w0=-3.8350167929700635e+21, w1=1.9291468278639606e+21
Gradient Descent(4/49): loss=3.07330405022888e+52, w0=1.9790229436117344e+28, w1=-9.956624464573812e+27
Gradient Descent(5/49): loss=8.186554010057928e+65, w0=-1.0213961374070557e+35, w1=5.1387786029758915e+34
Gradient Descent(6/49): loss=2.1807040718745378e+79, w0=5.271590450596744e+41, w1=-2.6522087791218953e+41
Gradient Descent(7/49): loss=5.808879100107509e+92, w0=-2.7207549931381356e+48, w1=1.3688488954091529e+48
Gradient Descent(8/49): loss=1.5473477962858158e+106, w0=1.4042267241312454e+55, w1=-7.064855954068589e+54
Gradient Descent(9/49): loss=4.121768006199722e+119, w0=-7.247446786275926e+61, w1=

[0.50000000000002487,
 1626615419033.354,
 4.3312670856189801e+25,
 1.1537452591800307e+39,
 3.0733040502288802e+52,
 8.1865540100579281e+65,
 2.1807040718745378e+79,
 5.8088791001075086e+92,
 1.5473477962858158e+106,
 4.1217680061997218e+119,
 1.097941363778161e+133,
 2.9246557217238705e+146,
 7.7905900741165735e+159,
 2.0752286586111265e+173,
 5.5279175833279461e+186,
 1.4725063034026385e+200,
 3.9224079970004133e+213,
 1.0448365796045093e+227,
 2.783197155712745e+240,
 7.413777961812516e+253,
 1.9748548375108215e+267,
 5.2605454996475504e+280,
 1.4012847136016367e+294,
 3.7326905521589186e+307,
 inf,
 inf,
 inf,
 inf,
 inf,
 inf,
 inf,
 inf,
 inf,
 inf,
 inf,
 inf,
 inf,
 inf,
 inf,
 inf,
 inf,
 inf,
 inf,
 inf,
 inf,
 inf,
 inf,
 nan,
 nan,
 nan]

#### Prediction

In [120]:
data = tx_test1
data.shape

(568238, 24)

In [121]:
y_pred = predict_labels(weights, data)

In [122]:
name = 'ye'
create_csv_submission(ids_test, y_pred, name)

## *Ridge regression    -------------------------------------------------------------------------------

In [12]:
gamma = 0.9
max_iters = 50
lambda_ = 1
#losses, weights = least_squares_GD(y, tx, initial_w, max_iters, gamma);
weights = ridge_regression(y, tx, lambda_);
print('losses: \n','\n\n','weights: \n',weights)
weights = np.array(weights).T#[-1,:] uncomment for gradient descent
weights.shape

losses: 
 

 weights: 
 [  2.60587944e-04  -9.09041953e-03  -2.05593759e-03  -2.07372712e-03
   4.16112316e-04   5.56555764e-04  -8.63582279e-03   1.49220972e-02
   8.84108508e-05   3.01001515e-03  -1.36439197e-02   2.91963352e-02
   5.90347247e-03   6.34020163e-03  -2.47827750e-04  -1.03790696e-03
   2.15291139e-03  -3.16656538e-04   7.13755800e-04   4.85803562e-03
   3.40155651e-04  -7.69669008e-04  -1.27454270e-02   1.51646839e-03
  -7.80900128e-04  -5.87028123e-04   3.16780195e-04   1.29177964e-03
   3.04952725e-04  -5.48271055e-03]


(30,)

#### Prediction

In [13]:
data = tx_test
data.shape

(568238, 30)

In [14]:
y_pred = predict_labels(weights, data)

In [15]:
name = 'ridge_regression'
create_csv_submission(ids_test, y_pred, name)