# Project 1

    We begin by loading the data

In [1]:
%matplotlib inline 
import numpy as np   # generic stuff
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

from lib.proj1_helpers import * #the helper provided for the project

from implementations import * #our implementations of the functions done by us
import datetime
from helpers import * #helpers of exo 2
# Useful starting lines



In [2]:
DATA_FOLDER = 'data/'

y, tx, ids = load_csv_data(DATA_FOLDER+'train.csv',sub_sample=True)

y_test, tx_test, ids_test = load_csv_data(DATA_FOLDER+'test.csv',sub_sample=True)

note that here we are only considering a sub_sample as the "True" value indicates

In [3]:
y

array([ 1., -1., -1., ...,  1., -1.,  1.])

In [4]:
tx

array([[ 138.47 ,   51.655,   97.827, ...,    1.24 ,   -2.475,  113.497],
       [ 219.057,   72.461,  124.835, ..., -999.   , -999.   ,   50.396],
       [  90.801,   27.787,   65.373, ..., -999.   , -999.   ,   62.766],
       ..., 
       [ 142.347,    7.389,   99.212, ..., -999.   , -999.   ,   97.068],
       [  78.162,   46.335,   60.136, ..., -999.   , -999.   ,   32.44 ],
       [ 130.042,    4.073,   67.819, ..., -999.   , -999.   ,   51.037]])

In [5]:
ids

array([100000, 100050, 100100, ..., 349850, 349900, 349950])

In [20]:
# illegal: 
import pandas as pd
pd.DataFrame(tx).head()

0       1        2        3       4        5        6      7       8   \
0  138.470  51.655   97.827   27.980    0.91  124.711    2.666  3.064  41.928   
1  219.057  72.461  124.835    5.506 -999.00 -999.000 -999.000  3.771  46.936   
2   90.801  27.787   65.373   55.978 -999.00 -999.000 -999.000  2.457  20.608   
3  128.167  52.145   86.912  103.373    0.90   47.636    4.808  2.277   1.936   
4  107.067   1.939   70.444   54.621 -999.00 -999.000 -999.000  2.079  30.366   

        9    ...        20       21   22      23     24     25       26  \
0  197.760   ...    -0.277  258.733  2.0  67.435  2.150  0.444   46.062   
1  122.986   ...     0.960   90.355  1.0  50.396 -0.708 -0.642 -999.000   
2  138.624   ...     0.880  219.339  1.0  62.766  0.778 -2.209 -999.000   
3  212.505   ...     2.802  292.582  2.0  72.406 -2.689 -0.295   31.252   
4  151.198   ...     1.190  290.199  1.0  66.634 -0.359 -0.485 -999.000   

        27       28       29  
0    1.240   -2.475  113.497  
1 -999.000 -999.000   50.396  
2 -999.000 -999.000   62.766  
3   -1.788   -0.287  103.658  
4 -999.000 -999.000   66.634  

[5 rows x 30 columns]

### Parameters

In [6]:
initial_w = np.zeros(tx.shape[1])
initial_w

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.])

In [7]:
gamma = 0.5
max_iters = 50
lambda_ = 1

### Methods

In [8]:
losses, weights = least_squares_GD(y, tx, initial_w, max_iters, gamma);

Gradient Descent(0/49): loss=0.5000000000000004, w0=57.80285280000054, w1=-14.487160400000011
Gradient Descent(1/49): loss=621856760293.665, w0=-62710489.517109506, w1=25606519.608812504
Gradient Descent(2/49): loss=5.046665008292038e+24, w0=168756041635167.1, w1=-72671335396127.39
Gradient Descent(3/49): loss=4.0971055023080493e+37, w0=-4.7964058454025653e+20, w1=2.0703943639389628e+20
Gradient Descent(4/49): loss=3.326216795350471e+50, w0=1.3664443268769607e+27, w1=-5.899133225068102e+26
Gradient Descent(5/49): loss=2.7003742747813633e+63, w0=-3.893358174576636e+33, w1=1.6808340549830917e+33
Gradient Descent(6/49): loss=2.1922868150761122e+76, w0=1.1093299077739105e+40, w1=-4.789184180221482e+39
Gradient Descent(7/49): loss=1.779798276277377e+89, w0=-3.1608027758526597e+46, w1=1.3645776187755836e+46
Gradient Descent(8/49): loss=1.4449212951773208e+102, w0=9.006044749720894e+52, w1=-3.888077820493091e+52
Gradient Descent(9/49): loss=1.173052911155607e+115, w0=-2.5660836250814015e+59, 

#### Prediction

In [13]:
weights = np.array(weights).T
weights.shape

(30, 51)

In [14]:
data = tx_test
data.shape

(11365, 30)

In [15]:
y_pred = predict_labels(weights, data)

/home/zampieri/Documents/EPFL/ML/LMO_ML/project1/lib/proj1_helpers.py:30: RuntimeWarning: invalid value encountered in less_equal
  y_pred[np.where(y_pred <= 0)] = -1
/home/zampieri/Documents/EPFL/ML/LMO_ML/project1/lib/proj1_helpers.py:31: RuntimeWarning: invalid value encountered in greater
  y_pred[np.where(y_pred > 0)] = 1


In [16]:
name = 'ye'
create_csv_submission(ids_test, y_pred, name)

TypeError: only length-1 arrays can be converted to Python scalars